source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def shared_dependency
    pod "SocaCrypto", git: "https://github.com/zhuhaow/SocaCrypto.git", :tag => '0.1.1'
    pod "SocaCore", :path => "../"
end

def shared_test_dependency
    pod "Quick"
    pod "Nimble"
end

target 'SocaCoreiOS', :exclusive => true do
    shared_dependency
end

target 'SocaCoreiOSTests', :exclusive => true do
    shared_dependency
    
    shared_test_dependency
end

target 'SocaCoreOSX', :exclusive => true do
    platform :osx, '10.10'
    
    shared_dependency
end

target 'SocaCoreOSXTests', :exclusive => true do
    platform :osx, '10.10'
    
    shared_dependency
    
    shared_test_dependency
end